### ISSUE TITLE
Configure Middleman i18n 

### ISSUE THREAD

**Issue by tayfunoziserikan** [lab2023/hierapolis#2]
http://middlemanapp.com/advanced/localization/

**Locale file format**

``` yaml
en:
  hierapolis:
      hello: Hello world
```
